### ISSUE TITLE
Update program to take an array of drafts to scrape from scraper.conf

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/prospect-scraper-mddb-2022#10]
Currently, the program reads this line in scraper.conf to determine what draft year should be scraped:
https://github.com/Leagify/prospect-scraper-mddb-2022/blob/4b5436baa3af9a0c749b2d02614568673dc0d54b/scraper.conf#L8

The year is loaded in the program here:
https://github.com/Leagify/prospect-scraper-mddb-2022/blob/4b5436baa3af9a0c749b2d02614568673dc0d54b/Program.cs#L27-L40

It would be nice to get this information as an array, then run this scraping job for any values in the array.

An example of how an array is stored in the configuration file is right here:
https://github.com/Leagify/prospect-scraper-mddb-2022/blob/4b5436baa3af9a0c749b2d02614568673dc0d54b/scraper.conf#L7

The configuration uses [SharpConfig](https://github.com/cemdervis/SharpConfig) to read values.

**Comment by ashwin003** [comment]
Hello!
I would like to give this a shot if it is still available.

Safe to assume the URLs to scrape will follow the pattern 
`https://www.nflmockdraftdatabase.com/big-boards/{year}/consensus-big-board-{year}` ?

**Comment by zo0o0ot** [comment]
I always worry about assumptions, but you are correct that the format of the URLs seems to be consistent from 2016 to 2024.  I'm not sure about any future years, but there's a chance it will stay the same format.
