### ISSUE TITLE
Update .NET version used in dev container and in GitHub actions

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/prospect-scraper-mddb-2022#69]
.NET is getting updated more often.  This repo currently uses .NET 6 for the runtime and the github action that verifies that everything is building properly in pull requests.
Example of the PR action:
![image](https://github.com/Leagify/prospect-scraper-mddb-2022/assets/876146/bf0aa6e2-d5bb-487f-be6d-e19c2472e0b4)

Here's the GitHub Actions code:
https://github.com/Leagify/prospect-scraper-mddb-2022/blob/82aff16f238f56e4767055689557141f65e6309f/.github/workflows/dotnet5.yml#L1-L23

Here's the commit that made changes from .NET 5 to 6: https://github.com/Leagify/prospect-scraper-mddb-2022/commit/38dd342d0959126bec8f309cd2e8344fa9a16980

It would be nice to change the devcontainer as well.
Here's the commit that was used to change from .NET 5 to .NET 6: https://github.com/Leagify/prospect-scraper-mddb-2022/commit/7662f930f8678560b02ee84dfd8e5b054aa8e2e0

It seems that .NET 8 will come soon. Maybe November 13-14?
https://devblogs.microsoft.com/dotnet/announcing-dotnet-8-rc1/

We should change things to .NET 7 for now, then do the similar changes for .NET 8 when the official version 8 release happens.

**Comment by iotalex** [comment]
Hello, can you please assign this issue to me? I will try my best to resolve the issue and get things updated.

**Comment by zo0o0ot** [comment]
Sounds good! The issue is yours.  Let me know if you have any questions.

**Comment by zo0o0ot** [comment]
I made some small updates in #76 . We missed the github action, but I fixed it.  Also a friendly reminder for myself in the future: create a new codespace after changing the dotnet version, because rebuilding doesn't tend to work well.
