### ISSUE TITLE
Update .NET version in project and in Codespaces

### ISSUE THREAD

**Issue by zo0o0ot** [Leagify/prospect-scraper-mddb-2022#84]
This project runs in GitHub Codespaces.
It would be nice to update the .NET version.

The project is currently using .NET 7. It would be nice if the version were updated.

Check out #55, #75, #76, and #77 for examples of how .NET was updated for previous versions.

**Comment by umar-source** [comment]
Hey @zo0o0ot, 
I'd like to volunteer to update the .NET version of the project from .NET 7 to the latest version.

**Comment by umardevX** [comment]
Hi, @zo0o0ot 
I'd like to volunteer to update the .NET version of the project from .NET 7 to the latest version.

**Comment by zo0o0ot** [comment]
Sounds good.  Let me know if you have any questions or issues.

**Comment by umardevX** [comment]
Hey @zo0o0ot,
I make the required changes, build and run project on my local machine and i works perfectly. Let me know if i miss anything.

**Comment by zo0o0ot** [comment]
Fixed in #90
